// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMmHXva882dLhg0eyCX0tVEgWGObTHuY',
    appId: '1:916192934580:web:850eaf0101528f9cb075e1',
    messagingSenderId: '916192934580',
    projectId: 'verbabridge',
    authDomain: 'verbabridge.firebaseapp.com',
    storageBucket: 'verbabridge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMaQhwqFT1xeyG554Zg_l0chG-mzvB9JA',
    appId: '1:916192934580:android:7a72f42098bf9da0b075e1',
    messagingSenderId: '916192934580',
    projectId: 'verbabridge',
    storageBucket: 'verbabridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TGsDj-CRoc2PknceEo24yatNXEC2s2o',
    appId: '1:916192934580:ios:e0a1fb154cd8ddc5b075e1',
    messagingSenderId: '916192934580',
    projectId: 'verbabridge',
    storageBucket: 'verbabridge.firebasestorage.app',
    iosBundleId: 'com.example.verbabridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TGsDj-CRoc2PknceEo24yatNXEC2s2o',
    appId: '1:916192934580:ios:e0a1fb154cd8ddc5b075e1',
    messagingSenderId: '916192934580',
    projectId: 'verbabridge',
    storageBucket: 'verbabridge.firebasestorage.app',
    iosBundleId: 'com.example.verbabridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMmHXva882dLhg0eyCX0tVEgWGObTHuY',
    appId: '1:916192934580:web:b1a8c2f0143a7a0eb075e1',
    messagingSenderId: '916192934580',
    projectId: 'verbabridge',
    authDomain: 'verbabridge.firebaseapp.com',
    storageBucket: 'verbabridge.firebasestorage.app',
  );

}